name: portfolio
region: fra
static_sites:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: AliMertBOSTAN/portfolio
    build_command: npm run build
    output_dir: dist
    routes:
      - path: /
