name: portfolio
region: fra
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: AliMertBOSTAN/portfolio
    build_command: npm run build
    run_command: npm run preview
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /
